import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'


export default function Home() {
  const [ data, setData ] = useState({});
  const [location, setLocation] = useState("");
  const [weather, setWeather] = useState();
  const [feelsLike, setFeelsLike] = useState(0);
  const [windSpeed, setWindSpeed] = useState(0);
  const [temp, setTemp] = useState(0);
  const [errorMessage, setErrorMessage] = useState("");

  var apiKey = "8230fe59f5cdba5e84c4be78e1e1daed";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = (event) => {
    if(event.key === "Enter"){
      axios.get(url)
        .then((response) => {
          console.clear();
          setData(response.data)
          console.log(response.data)
          setWeather(response.data.weather)
          setFeelsLike(response.data.main.feels_like);
          setWindSpeed(response.data.wind.speed);
          setTemp(response.data.main.temp);
          setErrorMessage("")
        }).catch(err => {
          setErrorMessage("Please enter another location")
          console.log(err)
          setData({})
          setWeather()
        })
        setLocation('');
    }
  }


  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {errorMessage}
        <input 
          value = {location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter Location"
          onKeyDown={searchLocation}
          type="text"
        />
        
        {
          weather && weather.map((w, index) => {
            console.log(w);
            return(
              <div key={index}>
                <div className={styles.weatherBox}>
                  <div className={styles.title}>{data.name} </div>
                  <div className={styles.hi}>Feels like: </div>
                  <div className={styles.bye}>{feelsLike}<span className={styles.degree}>℃</span></div>
                  <div className={styles.hi}>Temp: </div>
                  <div className={styles.bye}>{temp}<span className={styles.degree}>℃</span></div>
                  <div className={styles.hi}>Wind Speed: </div>
                  <div className={styles.bye}>{windSpeed}<span className={styles.degree}>m/s</span></div>
                </div>
              </div>
            )
          })
        }
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
